# Generated by Django 6.0.1 on 2026-01-13 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/')),
                ('title', models.CharField(db_index=True, help_text='Product title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OUT_OF_STOCK', 'Out of Stock')], db_index=True, default='ACTIVE', help_text='Product status', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
