# Generated by Django 6.0.1 on 2026-01-14 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Level this product is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='level.level'),
        ),
    ]
