# Generated by Django 6.0.1 on 2026-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('product', '0002_product_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.AddField(
            model_name='product',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Levels this product is assigned to', related_name='products', to='level.level'),
        ),
    ]
