# Generated by Django 6.0.1 on 2026-01-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.IntegerField(db_index=True, default=0, help_text='Display position/order for the product (lower number = higher position)'),
        ),
    ]
