# Generated by Django 6.0.1 on 2026-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productreview_use_frozen_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='use_actual_price',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, always use product price (no 30-70%% agreed price). Set when inserted at position from frontend.'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price agreed for this user (30-70%% of balance when assigned); used for commission', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='use_actual_price',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this user sees product at actual price (no 30-70%%). Set when product is inserted at position for this user.'),
        ),
    ]
