# Generated by Django 6.0.1 on 2026-01-13 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(db_index=True, help_text='Level number', unique=True)),
                ('level_name', models.CharField(help_text='Name of the level', max_length=100)),
                ('required_points', models.IntegerField(default=0, help_text='Points required to reach this level')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate as percentage (e.g., 5.50 for 5.5%)', max_digits=5)),
                ('min_orders', models.IntegerField(default=0, help_text='Minimum number of orders required')),
                ('benefits', models.TextField(blank=True, help_text='Benefits description for this level', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Status of the level', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'ordering': ['level'],
            },
        ),
    ]
