# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_level_frozen_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='start_continuous_orders_after',
            field=models.IntegerField(blank=True, help_text='Continuous orders start after this many (e.g. 8 means add at position 9, 10, ...). If null, uses max(0, min_orders - 10).', null=True),
        ),
    ]
