# Generated by Django 6.0.1 on 2026-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_level_start_continuous_orders_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='price_max_percent',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Max % of balance for next product price (e.g. 70 for 70%%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='level',
            name='price_min_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Min % of balance for next product price (e.g. 30 for 30%%)', max_digits=5),
        ),
    ]
