# Generated by Django 6.0.1 on 2026-01-13 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction identifier', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('COMMISSION', 'Commission'), ('BONUS', 'Bonus')], db_index=True, help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('remark_type', models.CharField(blank=True, choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('COMMISSION', 'Commission'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty'), ('ADJUSTMENT', 'Adjustment'), ('OTHER', 'Other')], help_text='Type of remark', max_length=20, null=True)),
                ('remark', models.TextField(blank=True, help_text='Additional remarks or description', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Transaction status', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('member_account', models.ForeignKey(help_text='User account associated with this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'), models.Index(fields=['member_account', '-created_at'], name='transaction_member__2842bb_idx'), models.Index(fields=['status', '-created_at'], name='transaction_status_b84006_idx')],
            },
        ),
    ]
