# Generated by Django 6.0.1 on 2026-01-18 07:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(help_text='Name of the account holder', max_length=255)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=255)),
                ('account_number', models.CharField(db_index=True, help_text='Bank account number', max_length=100)),
                ('routing_number', models.CharField(blank=True, help_text='Bank routing number (optional)', max_length=50, null=True)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('BUSINESS', 'Business')], default='CHECKING', help_text='Type of bank account', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this account is active for withdrawals')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Whether this is the primary withdrawal account')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this withdrawal account', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Account',
                'verbose_name_plural': 'Withdrawal Accounts',
                'db_table': 'withdrawal_accounts',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='withdrawal__user_id_32ab07_idx'), models.Index(fields=['user', 'is_active'], name='withdrawal__user_id_123045_idx'), models.Index(fields=['user', 'is_primary'], name='withdrawal__user_id_fc4c0d_idx')],
            },
        ),
    ]
