# Generated by Django 6.0.1 on 2026-01-18 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_withdrawalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_account',
            field=models.ForeignKey(blank=True, help_text='Withdrawal account used for this transaction (if withdrawal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transaction.withdrawalaccount'),
        ),
    ]
