# Generated by Django 6.0.1 on 2026-01-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_withdrawal_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='withdrawalaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='withdrawalaccount',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='withdrawalaccount',
            name='routing_number',
        ),
        migrations.AddField(
            model_name='withdrawalaccount',
            name='crypto_network',
            field=models.CharField(choices=[('TRC20', 'TRC20'), ('USDT', 'USDT'), ('BTC', 'BTC'), ('USDC', 'USDC'), ('ETH', 'ETH')], default='TRC20', help_text='Crypto network (TRC20, USDT, BTC, USDC, ETH)', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalaccount',
            name='crypto_wallet_address',
            field=models.CharField(db_index=True, default='', help_text='Crypto wallet address', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalaccount',
            name='crypto_wallet_name',
            field=models.CharField(default='', help_text='Name of the crypto wallet', max_length=255),
        ),
    ]
