# Generated by Django 6.0.1 on 2026-01-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_withdrawalaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='crypto_network',
            field=models.CharField(choices=[('TRC20', 'TRC20'), ('USDT', 'USDT'), ('BTC', 'BTC'), ('USDC', 'USDC'), ('ETH', 'ETH')], help_text='Crypto network (TRC20, USDT, BTC, USDC, ETH)', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='crypto_wallet_address',
            field=models.CharField(db_index=True, help_text='Crypto wallet address', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='crypto_wallet_name',
            field=models.CharField(help_text='Name of the crypto wallet', max_length=255),
        ),
    ]
