# Generated by Django 6.0.1 on 2026-01-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='User account balance', max_digits=10),
        ),
    ]
