# Generated by Django 6.0.1 on 2026-01-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_training_account',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this is a training account created by an agent'),
        ),
        migrations.AddField(
            model_name='user',
            name='original_account',
            field=models.ForeignKey(blank=True, help_text='Link to original account if this is a training account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
