# Generated by Django 6.0.1 on 2026-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_update_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance_frozen_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shortfall when frozen (product price minus balance); shown when balance_frozen is True', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_winning_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom winning amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='matching_max_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Matching range max % (e.g. 70 for 70%%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='matching_min_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Matching range min % (e.g. 30 for 30%%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_draws',
            field=models.PositiveIntegerField(blank=True, help_text='Number of draws', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='winning_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Winning amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='withdrawal_max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum withdrawal amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='withdrawal_min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum withdrawal amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='withdrawal_needed_to_complete_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Withdrawal amount needed to complete order', max_digits=10, null=True),
        ),
    ]
