# Generated by Django 6.0.1 on 2026-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_add_completed_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matching_max_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max % of balance for product price (e.g. 70 for 70%). Default 70 if not set.', max_digits=5, null=True, verbose_name='Max %'),
        ),
        migrations.AddField(
            model_name='user',
            name='matching_min_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Min % of balance for product price (e.g. 30 for 30%). Default 30 if not set.', max_digits=5, null=True, verbose_name='Min %'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance_frozen_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount frozen (user balance moved here when insufficient for product). Credits while frozen add here. On completing frozen product, total balance = this + commission.', max_digits=10, null=True),
        ),
    ]
