# Generated by Django 6.0.1 on 2026-01-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Activity',
                'verbose_name_plural': 'Login Activities',
                'db_table': 'login_activities',
                'ordering': ['-login_time'],
            },
        ),
    ]
