# Generated by Django 6.0.1 on 2026-01-13 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['-login_time'], name='login_activ_login_t_afa50a_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', '-login_time'], name='login_activ_user_id_8ea72b_idx'),
        ),
    ]
